
[versions]

kotlin = "1.8.20"
googleTruth = "1.1.3"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]

truth = { group = "com.google.truth", name="truth", version.ref = "googleTruth" }
kotlin-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }